# Generated by Django 5.2.15 on 2026-06-09 16:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, help_text='Формат: +7(***)-***-**-**', max_length=20, null=True, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер'), ('CARRIER', 'Перевозчик')], default='CLIENT', max_length=20, verbose_name='Роль')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Уникальный ID пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='encar', max_length=32, verbose_name='Источник')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='Код источника')),
                ('name_ko', models.CharField(max_length=255, verbose_name='Название (источник)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['name_en', 'name_ko'],
                'unique_together': {('source', 'name_ko')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='KRW', max_length=8, verbose_name='Базовая валюта')),
                ('quote', models.CharField(default='RUB', max_length=8, verbose_name='Котируемая валюта')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Курс (quote за 1 base)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'unique_together': {('base', 'quote')},
            },
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='encar', max_length=32, verbose_name='Источник')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='Код источника')),
                ('name_ko', models.CharField(max_length=255, verbose_name='Название (источник)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_groups', to='cars.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Группа моделей',
                'verbose_name_plural': 'Группы моделей',
                'ordering': ['brand__name_en', 'name_en', 'name_ko'],
                'unique_together': {('brand', 'name_ko')},
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='encar', max_length=32, verbose_name='Источник')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='Код источника')),
                ('name_ko', models.CharField(max_length=255, verbose_name='Название (источник)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('model_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.modelgroup', verbose_name='Группа моделей')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['model_group__brand__name_en', 'name_en', 'name_ko'],
                'unique_together': {('model_group', 'name_ko')},
            },
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('source', models.CharField(default='encar', max_length=32, verbose_name='Источник')),
                ('extra_q', models.JSONField(blank=True, default=dict, verbose_name='Доп. параметры q')),
                ('page_size', models.IntegerField(default=100, help_text='Записей за запрос к list/mobile (до 1000)', verbose_name='Размер страницы')),
                ('max_pages', models.IntegerField(default=5, verbose_name='Макс. страниц за прогон')),
                ('backfill_completed', models.BooleanField(default=False, help_text='После полной первичной выгрузки включается ранний останов', verbose_name='Полная выгрузка завершена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='cars.brand', verbose_name='Марка')),
                ('model_group', models.ForeignKey(blank=True, help_text='Пусто = все модели марки', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='cars.modelgroup', verbose_name='Группа моделей')),
            ],
            options={
                'verbose_name': 'Профиль импорта',
                'verbose_name_plural': 'Профили импорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='encar', max_length=32, verbose_name='Источник')),
                ('external_id', models.CharField(db_index=True, max_length=64, verbose_name='ID в источнике')),
                ('source_country', models.CharField(default='KR', max_length=8, verbose_name='Страна источника')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='Ссылка на источник')),
                ('source_metadata', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные источника')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='VIN номер')),
                ('badge', models.CharField(blank=True, default='', max_length=255, verbose_name='Комплектация')),
                ('price_krw', models.BigIntegerField(blank=True, null=True, verbose_name='Цена (KRW, воны)')),
                ('origin_price_krw', models.BigIntegerField(blank=True, null=True, verbose_name='Цена нового (KRW, воны)')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег (км)')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска')),
                ('year_month', models.IntegerField(blank=True, null=True, verbose_name='Год-месяц (YYYYMM)')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Бензин'), ('DIESEL', 'Дизель'), ('HYBRID', 'Гибрид'), ('ELECTRIC', 'Электричество'), ('LPG', 'Газ (LPG)'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип топлива')),
                ('fuel_type_raw', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип топлива (оригинал)')),
                ('engine_volume', models.FloatField(blank=True, null=True, verbose_name='Объем двигателя (см³)')),
                ('transmission', models.CharField(blank=True, default='', max_length=50, verbose_name='Коробка передач')),
                ('transmission_raw', models.CharField(blank=True, default='', max_length=50, verbose_name='КПП (оригинал)')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет')),
                ('color_raw', models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет (оригинал)')),
                ('color_hex', models.CharField(blank=True, default='', max_length=16, verbose_name='Цвет (HEX)')),
                ('body_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип кузова')),
                ('seat_count', models.IntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='Регион продавца')),
                ('region_raw', models.CharField(blank=True, default='', max_length=100, verbose_name='Регион (оригинал)')),
                ('sales_status', models.CharField(choices=[('ON_SALE', 'В продаже'), ('CONTRACT', 'Бронь / договор'), ('SOLD', 'Продан')], default='ON_SALE', max_length=20, verbose_name='Статус продажи')),
                ('has_accident_record', models.BooleanField(blank=True, null=True, verbose_name='Есть записи об авариях')),
                ('description_ko', models.TextField(blank=True, default='', verbose_name='Описание (оригинал)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('listed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата размещения')),
                ('modified_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата изменения в источнике')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Впервые обнаружено')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='В последний раз встречено')),
                ('detail_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Дозагружена деталь')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Марка')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model', verbose_name='Модель')),
                ('model_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.modelgroup', verbose_name='Группа моделей')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-first_seen_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Снапшот цены в рублях на момент оформления', max_digits=14, verbose_name='Итоговая цена заказа (RUB)')),
                ('status', models.CharField(choices=[('REVIEW', 'На рассмотрении'), ('APPLICATION', 'Оформление заявки'), ('AWAITING_PAYMENT', 'Ожидается оплата'), ('PURCHASE', 'Выкуп автомобиля'), ('TO_WAREHOUSE_KR', 'В пути на склад (Корея)'), ('AT_WAREHOUSE_KR', 'Прибыл на склад (Корея)'), ('DOCUMENTS', 'Подготовка документов'), ('SHIPPING_PREP', 'Подготовка к отправке'), ('TO_BORDER', 'В пути на границу'), ('CUSTOMS', 'Таможенное оформление'), ('TO_WAREHOUSE_RU', 'В пути на склад (Россия)'), ('TO_DESTINATION', 'В пути в город назначения'), ('DELIVERED', 'Автомобиль передан клиенту'), ('CANCELLED', 'Отменён')], default='REVIEW', max_length=30, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cars.car', verbose_name='Автомобиль')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REVIEW', 'На рассмотрении'), ('APPLICATION', 'Оформление заявки'), ('AWAITING_PAYMENT', 'Ожидается оплата'), ('PURCHASE', 'Выкуп автомобиля'), ('TO_WAREHOUSE_KR', 'В пути на склад (Корея)'), ('AT_WAREHOUSE_KR', 'Прибыл на склад (Корея)'), ('DOCUMENTS', 'Подготовка документов'), ('SHIPPING_PREP', 'Подготовка к отправке'), ('TO_BORDER', 'В пути на границу'), ('CUSTOMS', 'Таможенное оформление'), ('TO_WAREHOUSE_RU', 'В пути на склад (Россия)'), ('TO_DESTINATION', 'В пути в город назначения'), ('DELIVERED', 'Автомобиль передан клиенту'), ('CANCELLED', 'Отменён')], max_length=30, verbose_name='Статус этапа')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='order_media/%Y/%m/%d/', verbose_name='Медиафайл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фиксации')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cars.order', verbose_name='Заказ')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Кто загрузил отчет', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'Истории статусов заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска (от)')),
                ('year_max', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска (до)')),
                ('mileage_min', models.IntegerField(blank=True, null=True, verbose_name='Пробег от (км)')),
                ('mileage_max', models.IntegerField(blank=True, null=True, verbose_name='Пробег до (км)')),
                ('min_engine_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min объём двигателя (л)')),
                ('max_engine_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max объём двигателя (л)')),
                ('fuel_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип топлива')),
                ('body_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип кузова')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена от (RUB)')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена до (RUB)')),
                ('transmission', models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач')),
                ('colors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвета')),
                ('status', models.CharField(choices=[('TRACKED', 'Отслеживается'), ('CANCELLED', 'Отменен')], default='TRACKED', max_length=20, verbose_name='Статус запроса')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Watermark: авто, обнаруженные позже этой метки, ещё не проверялись', null=True, verbose_name='Последняя проверка')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Марка')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model', verbose_name='Модель')),
                ('model_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.modelgroup', verbose_name='Группа моделей')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на поиск',
                'verbose_name_plural': 'Запросы на поиск',
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Путь')),
                ('ordering', models.FloatField(default=0, verbose_name='Порядок')),
                ('category', models.CharField(blank=True, default='', max_length=20, verbose_name='Категория')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фото автомобилей',
                'ordering': ['ordering'],
                'unique_together': {('car', 'path')},
            },
        ),
    ]
