# Generated by Django 6.0.5 on 2026-06-01 12:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, help_text='Формат: +7(***)-***-**-**', max_length=20, null=True, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер'), ('CARRIER', 'Перевозчик')], default='CLIENT', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, verbose_name='VIN номер')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Бензин'), ('ELECTRIC', 'Электричество'), ('DIESEL', 'Дизель'), ('HYBRID', 'Гибрид')], max_length=20, verbose_name='Тип топлива')),
                ('engine_volume', models.FloatField(blank=True, null=True, verbose_name='Объем двигателя (л/см³)')),
                ('engine_power', models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('transmission', models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач')),
                ('steering_wheel', models.CharField(blank=True, choices=[('LEFT', 'Левый'), ('RIGHT', 'Правый')], max_length=10, null=True, verbose_name='Расположение руля')),
                ('drive_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Привод')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('seller_country', models.CharField(default='Южная Корея', max_length=50, verbose_name='Страна продавца')),
                ('manufacturer_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производителя')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена автомобиля')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('condition', models.TextField(verbose_name='Состояние автомобиля')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN номер')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Марка')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model', verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена заказа')),
                ('status', models.CharField(choices=[('PROCESSING', 'В обработке'), ('WAREHOUSE_KR', 'Доставлен на склад (Корея)'), ('IN_TRANSIT_BORDER', 'В пути на границу'), ('AT_BORDER', 'На границе'), ('WAREHOUSE_RU', 'Доставлен на склад (Россия)'), ('IN_TRANSIT_RU', 'В пути по России'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='PROCESSING', max_length=30, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cars.car', verbose_name='Автомобиль')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSING', 'В обработке'), ('WAREHOUSE_KR', 'Доставлен на склад (Корея)'), ('IN_TRANSIT_BORDER', 'В пути на границу'), ('AT_BORDER', 'На границе'), ('WAREHOUSE_RU', 'Доставлен на склад (Россия)'), ('IN_TRANSIT_RU', 'В пути по России'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], max_length=30, verbose_name='Статус этапа')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='order_media/%Y/%m/%d/', verbose_name='Медиафайл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фиксации')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cars.order', verbose_name='Заказ')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Кто загрузил отчет', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'Истории статусов заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска (от)')),
                ('year_max', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска (до)')),
                ('mileage_min', models.IntegerField(blank=True, null=True, verbose_name='Пробег от (км)')),
                ('mileage_max', models.IntegerField(blank=True, null=True, verbose_name='Пробег до (км)')),
                ('min_engine_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min Объем двигателя')),
                ('max_engine_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max Объем двигателя')),
                ('min_engine_power', models.IntegerField(blank=True, null=True, verbose_name='Min Мощность двигателя')),
                ('max_engine_power', models.IntegerField(blank=True, null=True, verbose_name='Max Мощность двигателя')),
                ('fuel_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип топлива')),
                ('condition', models.CharField(blank=True, max_length=20, null=True, verbose_name='Состояние')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена от')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена до')),
                ('transmission', models.CharField(blank=True, max_length=50, null=True, verbose_name='Запрашиваемая Коробка передач')),
                ('steering_wheel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Запрашиваемое Расположение руля')),
                ('drive_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Запрашиваемый Привод')),
                ('colors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Запрашиваемые Цвета')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Запрашиваемая Страна')),
                ('status', models.CharField(choices=[('TRACKED', 'Отслеживается'), ('CANCELLED', 'Отменен')], default='TRACKED', max_length=20, verbose_name='Статус запроса')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Марка')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model', verbose_name='Модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на поиск',
                'verbose_name_plural': 'Запросы на поиск',
            },
        ),
    ]
