# Generated by Django 6.0.5 on 2026-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars'),
        ('cars', '0002_user_telegram_id'),
    ]

    operations = [
    ]
